AssetによるFilterをCoinSelectionに追加
cryptogarageinc/cg-cfd pull request #66
Opened 2019-11-13 12:43 UTC by fujita-cg

## 関連Issue

- [#947](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/947)

## 概要

- cfd-js
  - AssetFilterに合わせて、json I/Fを修正
  - SelectUtxosのテストコード修正
- cfd
  - Targetを複数指定できるSelectCoins関数の追加
  - AssetFilterの処理を追加
  - テストコードを変更に合わせて修正

## 使い方

```bash
npm run check_all
or 
npm run cmake_all && npm run check
```

## 今回保留した項目とTODO

- 

## 確認項目

**PRを出した人**

- [ ] チェックスクリプトでチェックを実施した 
- [x] 正常にビルドできた
- [x] 関連チケットに実績をつけた
- [x] ZenHubでPRとIssueを関連付けた
- [x] ZenHubのIssueを `Review/QA` Pipelineに移した

**レビューする人**

- [ ] 関連チケットにレビュー実績をつけた

## 備考

まだ途中のためDraft

2019-11-14 06:33 UTC, k-matsuzawa requested changes
確認お願いします。

2019-11-14 06:33 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>        if (target_asset.GetHex() == ConfidentialAssetId(asset_byte).GetHex()) {
最適化回りにどうしても目が行ってしまうので、指摘を。

> 211: ConfidentialAssetId target_asset(target.first);

上記ですが、以下のように定義するといいと思います。
208-9: std::string target_asset = ConfidentialAssetId(target.first).GetHex();

core層の不具合件（先ほど話した内容）は後で直しておきます、、

2019-11-14 06:33 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>  #endif
filterのチェックについてです。以下、filter設定時の挙動について微妙な点があります。
1. if ((!filter.target_asset.IsEmpty()) && (!target.first.empty())) の場合、target_assetと不一致ならループをスルーすべきではないか？
  (上記は修正前のコードですが、↑のチェック対象は引数のfilter値です)
2. if (!target.first.empty()) が false (else) の場合、work_filterを初期化すべきではないでしょうか。
  (前回のfilter値が残ってしまう)

2019-11-14 06:33 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
> +      }
ここの処理で使っているtarget_assetですが、以下に変更したうえで上記の309の後くらいで以下を設定するのがいいかと思います。

309付近
```
std::vector<uint8_t> target_asset_bytes;
if (!target_asset.IsEmpty()) {
  target_asset_bytes = target_asset.GetData().GetBytes();
}
```

今回箇所
```
if (!target_asset_bytes.empty() &&
    memcmp(utxo->asset, target_asset_bytes.data(), sizeof(utxo->asset)) != 0) {
```

2019-11-14 06:33 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
> +          memcmp(utxo->asset, target_asset.GetData().GetBytes().data(), sizeof(utxo->asset)) != 0) {
ここも同上(L329付近)です。

2019-11-14 06:36 UTC, fujita-cg commented on src/cfd_utxo.cpp
>        if (target_asset.GetHex() == ConfidentialAssetId(asset_byte).GetHex()) {
🙇

2019-11-14 07:18 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>  #endif
その後に話したことのメモ。
- UtxoFilterからtarget_assetを外す。
- target_assetはMinConfの引数に移動。
- 上記に合わせて、target.firstをそのままフィルタ対象assetとして渡す。
    - btc用の関数は分ける。

2019-11-14 07:21 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>  #endif
さらに追記。
- filter処理はSelectCoinsに移動して、assetのチェックはMinConfから除外する。
    -> この方がシンプル。

2019-11-14 07:22 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
> +      }
追記。

filter処理はSelectCoinsに移動して、assetのチェックはMinConfから除外する。
-> この方がシンプル。

2019-11-15 00:54 UTC, k-matsuzawa commented
unused parameterとなっている箇所だけ対策入れさせていただきました。m(_ _)m

2019-11-15 01:42 UTC, k-matsuzawa requested changes
確認してコメントしました！

2019-11-15 01:42 UTC, k-matsuzawa commented on include/cfd/cfd_utxo.h
> +      Amount* utxo_fee_value = nullptr, std::map<std::string, bool>* map_searched_bnb = nullptr);
よく見たらSelectCoinsMinConfの頃からの不具合だったのですが、必須パラメータ `map_select_value` に初期値として、不許可であるnullptrを設定するのは不適切と思いました。ここだけ外していただければ。
（MinConfも、、m(_ _)m）
bitcoin版はnullptr許可なのでOKです。

2019-11-15 01:42 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>        if (target_asset.GetHex() == ConfidentialAssetId(asset_byte).GetHex()) {
> if (target_asset.GetHex() == ConfidentialAssetId(asset_byte).GetHex()) {

上記の `target_asset.GetHex()` は、target_assetのコンストラクタ時点で文字列の保証がすでに取れている箇所であるため、 `target.first` をそのまま使ってもいいと思います。

2019-11-15 01:42 UTC, k-matsuzawa commented on src/cfd_utxo.cpp
>    }
（口頭で説明済み）fee_assetについて、feeRate=0の場合に本処理を行うと、利用者がFeeAssetのUTXOを設定していないのに参照しようとして、エラーが返るケースが出てくる。よってFee未使用の場合についての考慮が必要。
（例：settlenetでいうと、L-JPYのみCoinSelectionしようとして、L-JPYのみのUTXOを渡したのに、(fee assetであるL-BTCの探索を行おうとしてしまい) L-BTCがないというエラーが返却されてしまうイメージ）

2019-11-15 03:36 UTC, fujita-cg commented on src/cfd_utxo.cpp
>    }
こちらについては、EffectiveFeeBaseRate()の設定有無の判定を追加しました。 2d78731

2019-11-15 03:37 UTC, fujita-cg commented on include/cfd/cfd_utxo.h
> +      Amount* utxo_fee_value = nullptr, std::map<std::string, bool>* map_searched_bnb = nullptr);
初期値として、map_select_value, select_valueからは、一律nullptrの初期値を削除しました！ 2d78731

2019-11-15 03:45 UTC, fujita-cg commented on src/cfd_utxo.cpp
>        if (target_asset.GetHex() == ConfidentialAssetId(asset_byte).GetHex()) {
こちら修正しました。 8222e62

2019-11-15 05:18 UTC, k-matsuzawa approved these changes

2019-11-15 05:18 UTC, merged